version: "3.2"
services:
  api:
    container_name: tmt
    image: tmt:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - ${APP_PORT:-8000}:8000
    environment:
      DEBUG_MODE: "True"
      TMT_DJANGO_SECRET_KEY: "django-insecure-mz)!@0ornp#gih#e&e#))699tfou%4u=uj#w0l#l_io+z=n1r)"
      TMT_JWT_EXPIRATION_DELTA_MINUTES: 30