version: "3.2"
services:
  api:
    container_name: tmt
    image: tmt:${APP_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver
    ports:
      - ${APP_PORT:-8000}:8000
    environment:
      DEBUG_MODE: "True"